### ISSUE TITLE
error while trying to copy boilerplate

### ISSUE THREAD

**Issue by omkelderman** [michaelowens/wilfred#6]
I have no clue why this doesnt work, since it worked for me before.....

![error](http://omk.pics/1/tw5ir.png)

and yes this also happens when i use the interactive mode

**Comment by michaelowens** [comment]
Could you post the contents of `~/.wilfred.json` ? @omkelderman

**Comment by omkelderman** [comment]
``` json
{
  "boilerplates": [
    {
      "boilerplate": "nodejs-express-app",
      "path": "/home/olle/wilfred-boilerplates/nodejs-expressjs-app"
    }
  ]
}
```

and yes, that path exists :P

**Comment by rasmuswoelk** [comment]
I'm getting the same error. Any suggestions?

**Comment by omkelderman** [comment]
> Any suggestions?

For now, don't use node v0.10 ^^

**Comment by rasmuswoelk** [comment]
Alright - what version are you using?

**Comment by omkelderman** [comment]
see the last lines in the screenshot ^^

**Comment by rasmuswoelk** [comment]
Oh, thanks :)

**Comment by omkelderman** [comment]
Which was btw the only version i tried, so I'm not saying others don't work, just try whatever and see what happens :P

**Comment by michaelowens** [comment]
The current LTS/stable release for node is v4, so I don't think I want to make changes just for running on older versions. Node (and javascript) move fast, so as long as it runs on stable I'm good with that (and I think it should work with v4 as well as with v5).

**Comment by omkelderman** [comment]
can confirm on v4
![v4](http://omk.pics/1/2Tk8f.png)

(did `nvm install v4`, so not sure if that means there are early v4-versions or something where it didnt work...)

**Comment by michaelowens** [comment]
Thanks for confirming it works on stable release!
